# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d8c32fb372a75a375878acef553e5dc0716c97151c533bd34dc85a69000aedf0c6efe24e6961a7107ac74b8bdc26da7107e9f60f0038b3ce571134ecd61b745

test:
  secret_key_base: 3742e89bbf7c5052288dec519a7fec7844a397b61890ecbfc05e30d0c3c6d1eec5bc7295a6711311dc0f3c4709c7e644e9fb6291ae10f032ff480e8392590fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
